### ISSUE TITLE
Connect Android devices to `adb` wirelessly.

### ISSUE THREAD

**Issue by garg3133** [nightwatchjs/mobile-helper-tool#19]
* Document the process to connect to the android devices wirelessly, so that we don't need to connect an Android device using USB Cable to automate it.
* Add the same ability in the tool itself, which can be triggered by running `npx @nightwatch/mobile-helper android --connect --wireless` command, which will then prompt for the Android device's IP address, port and pairing code and set up a wireless connection.

During this process, we should also guide users on the steps they should follow on their Android Device to establish a connection.

Refer: https://developer.android.com/tools/adb#wireless-android11-command-line

**Comment by Biki-das** [comment]
@garg3133 tried to dig this one up, was able to write the nodejs script that can do the same, only thing now i need to dig dive in how to add this up with the nightwatch commands below how the script to connect adb is working.

is the `index.ts` file is the one responsible for all the logic for the adb? could you provide some pointers on the same?


https://github.com/nightwatchjs/mobile-helper-tool/assets/72331432/f909c5f7-2f4b-419f-979e-7d538cc28dd3

**Comment by garg3133** [comment]
@Biki-das Cool. Yes, that file is the entry point for the `android` command, but you can have the logic for wireless pairing of device in a separate file as well, and then link it up in that file.
