### ISSUE TITLE
Can't initialize nightwatch with ios

### ISSUE THREAD

**Issue by 8ucik** [nightwatchjs/mobile-helper-tool#41]
When I try to initialize nightwatch helper with the following command:

`npx @nightwatch/mobile-helper ios `

I get the following in return. 
`npx @nightwatch/mobile-helper ios --setup
unknown option(s) passed: standalone

Usage: npx @nightwatch/mobile-helper ios [options]
  Verify if all the requirements are met to run tests on an iOS device/simulator.

Options:
  --help, -h .............. Help for ios command.                                                                              
  --setup, --install, -i .. Instruction to setup all the missing requirements.                                                 
  --mode, -m .............. Verify/setup requirements for real-device or simulator. Available args: "real", "simulator", "both"
  --appium ................ Make sure the final setup works with Appium out-of-the-box.                `

I looks like the standalone flag is responding to ios as well.

Could someone please help?

**Comment by garg3133** [comment]
@itsspriyansh Can you look into this?

**Comment by itsspriyansh** [comment]
@8ucik Hey, thanks for pointing this out! This issue arised due to `standalone` key being passed to the ios script in the `options` object.
I have commited the changes to a previously open PR #36 that should fix the issue. 
@garg3133 Will you please review it?

**Comment by garg3133** [comment]
Fixed in #36. It should work fine in `v0.1.14`.
